package com.noop.analytics

import org.junit.Assert.assertEquals
import org.junit.Test

/**
 * Swift-oracle parity for the Charge driver verdicts (ChargeDrivers.swift <-> RecoveryDrivers.kt).
 *
 * EXPECTED is the verbatim stdout of the Swift `RecoveryScorer.chargeDrivers` run over the same grid
 * (HRV, resting HR and respiration either side of their baselines and on the display-rounding edges,
 * skin-temperature drift inside and outside the old fixed band, two sleep qualities). Each row is
 * `label/points/verdict`, sorted, with the verdict as the Swift catalog string. A verdict must agree with
 * the row's printed values and points on both platforms, so the Kotlin twin must reproduce every line.
 */
class ChargeDriverVerdictOracleTest {

    private fun baseline(mean: Double, sigma: Double): BaselineState =
        BaselineState(
            baseline = mean, spread = sigma / 1.253, nValid = 14, nightsSinceUpdate = 0,
            status = BaselineStatus.TRUSTED,
        )

    private val labelText = mapOf(
        ChargeDriverLabel.HEART_RATE_VARIABILITY to "Heart rate variability",
        ChargeDriverLabel.RESTING_HEART_RATE to "Resting heart rate",
        ChargeDriverLabel.SLEEP_QUALITY to "Sleep quality",
        ChargeDriverLabel.RESPIRATORY_RATE to "Respiratory rate",
        ChargeDriverLabel.SKIN_TEMPERATURE to "Skin temperature",
    )

    /** The Swift verdict string for each Kotlin verdict: the engine-to-catalog contract both share. */
    private val verdictText = mapOf(
        ChargeDriverVerdict.ABOVE_BASELINE_SUPPORTING to "above baseline, supporting recovery",
        ChargeDriverVerdict.BELOW_BASELINE_SUPPORTING to "below baseline, supporting recovery",
        ChargeDriverVerdict.ABOVE_BASELINE_LIMITING to "above baseline, limiting recovery",
        ChargeDriverVerdict.BELOW_BASELINE_LIMITING to "below baseline, limiting recovery",
        ChargeDriverVerdict.AT_BASELINE to "at baseline",
        ChargeDriverVerdict.HRV_SATURATION_LIMITING to
            "below baseline, limiting recovery, though low resting HR suggests this may be parasympathetic saturation rather than fatigue",
        ChargeDriverVerdict.STRONG_NIGHT_SUPPORTING to "a strong night, supporting recovery",
        ChargeDriverVerdict.BELOW_GOOD_NIGHT_LIMITING to "below a good night, limiting recovery",
        ChargeDriverVerdict.TYPICAL_NIGHT to "a typical night",
        ChargeDriverVerdict.NEAR_BASELINE to "near baseline",
        ChargeDriverVerdict.WARMER_THAN_BASELINE_LIMITING to "warmer than baseline, limiting recovery",
        ChargeDriverVerdict.COOLER_THAN_BASELINE_LIMITING to "cooler than baseline, limiting recovery",
        ChargeDriverVerdict.SLIGHTLY_ABOVE_BASELINE_SUPPORTING to "slightly above baseline, supporting recovery",
        ChargeDriverVerdict.SLIGHTLY_BELOW_BASELINE_SUPPORTING to "slightly below baseline, supporting recovery",
        ChargeDriverVerdict.SLIGHTLY_ABOVE_BASELINE_LIMITING to "slightly above baseline, limiting recovery",
        ChargeDriverVerdict.SLIGHTLY_BELOW_BASELINE_LIMITING to "slightly below baseline, limiting recovery",
        ChargeDriverVerdict.ABOVE_BASELINE_TOO_SMALL to "above baseline, too small to change Charge",
        ChargeDriverVerdict.BELOW_BASELINE_TOO_SMALL to "below baseline, too small to change Charge",
    )

    @Test fun everyVerdictHasItsSwiftString() {
        assertEquals(ChargeDriverVerdict.entries.toSet(), verdictText.keys)
    }

    @Test fun verdictsMatchTheSwiftOracle() {
        for (line in EXPECTED.trim().lines()) {
            val (inputs, expected) = line.split("|", limit = 2)
            val (hrv, rhr, resp, skin, sp) = inputs.split(",").map { it.toDouble() }
            val rows = RecoveryDrivers.chargeDrivers(
                hrv = hrv, rhr = rhr, resp = resp,
                hrvBaseline = baseline(30.0, 6.0), rhrBaseline = baseline(58.0, 3.0),
                respBaseline = baseline(16.0, 2.0), sleepPerf = sp, skinTempDev = skin,
            ).map { "${labelText.getValue(it.label)}/${it.deltaPoints}/${verdictText.getValue(it.verdict)}" }
                .sorted()
                .joinToString(";")
            assertEquals("inputs $inputs", expected, rows)
        }
    }

    private companion object {
        val EXPECTED = """
29.6,57.7,15.97,0.1,0.6|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
29.6,57.7,15.97,0.1,0.9|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
29.6,57.7,15.97,0.25,0.6|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
29.6,57.7,15.97,0.25,0.9|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
29.6,57.7,15.97,-0.5,0.6|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/-12/below a good night, limiting recovery
29.6,57.7,15.97,-0.5,0.9|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/2/a strong night, supporting recovery
29.6,57.7,16.04,0.1,0.6|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
29.6,57.7,16.04,0.1,0.9|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
29.6,57.7,16.04,0.25,0.6|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
29.6,57.7,16.04,0.25,0.9|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
29.6,57.7,16.04,-0.5,0.6|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/-12/below a good night, limiting recovery
29.6,57.7,16.04,-0.5,0.9|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/2/a strong night, supporting recovery
29.6,57.7,17.5,0.1,0.6|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
29.6,57.7,17.5,0.1,0.9|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
29.6,57.7,17.5,0.25,0.6|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
29.6,57.7,17.5,0.25,0.9|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
29.6,57.7,17.5,-0.5,0.6|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/-12/below a good night, limiting recovery
29.6,57.7,17.5,-0.5,0.9|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/2/a strong night, supporting recovery
29.6,58.3,15.97,0.1,0.6|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
29.6,58.3,15.97,0.1,0.9|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
29.6,58.3,15.97,0.25,0.6|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
29.6,58.3,15.97,0.25,0.9|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
29.6,58.3,15.97,-0.5,0.6|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/-12/below a good night, limiting recovery
29.6,58.3,15.97,-0.5,0.9|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/2/a strong night, supporting recovery
29.6,58.3,16.04,0.1,0.6|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
29.6,58.3,16.04,0.1,0.9|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
29.6,58.3,16.04,0.25,0.6|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
29.6,58.3,16.04,0.25,0.9|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
29.6,58.3,16.04,-0.5,0.6|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/-12/below a good night, limiting recovery
29.6,58.3,16.04,-0.5,0.9|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/2/a strong night, supporting recovery
29.6,58.3,17.5,0.1,0.6|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
29.6,58.3,17.5,0.1,0.9|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
29.6,58.3,17.5,0.25,0.6|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
29.6,58.3,17.5,0.25,0.9|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
29.6,58.3,17.5,-0.5,0.6|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/-12/below a good night, limiting recovery
29.6,58.3,17.5,-0.5,0.9|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/2/a strong night, supporting recovery
29.6,61.0,15.97,0.1,0.6|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/-8/above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
29.6,61.0,15.97,0.1,0.9|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/-8/above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
29.6,61.0,15.97,0.25,0.6|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/-8/above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
29.6,61.0,15.97,0.25,0.9|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/-8/above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
29.6,61.0,15.97,-0.5,0.6|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/-8/above baseline, limiting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/-12/below a good night, limiting recovery
29.6,61.0,15.97,-0.5,0.9|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/-8/above baseline, limiting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/2/a strong night, supporting recovery
29.6,61.0,16.04,0.1,0.6|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/-8/above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
29.6,61.0,16.04,0.1,0.9|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/-8/above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
29.6,61.0,16.04,0.25,0.6|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/-8/above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
29.6,61.0,16.04,0.25,0.9|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/-8/above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
29.6,61.0,16.04,-0.5,0.6|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/-8/above baseline, limiting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/-12/below a good night, limiting recovery
29.6,61.0,16.04,-0.5,0.9|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/-8/above baseline, limiting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/2/a strong night, supporting recovery
29.6,61.0,17.5,0.1,0.6|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/-8/above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
29.6,61.0,17.5,0.1,0.9|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/-8/above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
29.6,61.0,17.5,0.25,0.6|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/-8/above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
29.6,61.0,17.5,0.25,0.9|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/-8/above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
29.6,61.0,17.5,-0.5,0.6|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/-8/above baseline, limiting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/-12/below a good night, limiting recovery
29.6,61.0,17.5,-0.5,0.9|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/-8/above baseline, limiting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/2/a strong night, supporting recovery
29.6,55.0,15.97,0.1,0.6|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/8/below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
29.6,55.0,15.97,0.1,0.9|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/7/below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
29.6,55.0,15.97,0.25,0.6|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/8/below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
29.6,55.0,15.97,0.25,0.9|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/8/below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
29.6,55.0,15.97,-0.5,0.6|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/8/below baseline, supporting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/-12/below a good night, limiting recovery
29.6,55.0,15.97,-0.5,0.9|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/8/below baseline, supporting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/2/a strong night, supporting recovery
29.6,55.0,16.04,0.1,0.6|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/8/below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
29.6,55.0,16.04,0.1,0.9|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/7/below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
29.6,55.0,16.04,0.25,0.6|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/8/below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
29.6,55.0,16.04,0.25,0.9|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/8/below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
29.6,55.0,16.04,-0.5,0.6|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/8/below baseline, supporting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/-12/below a good night, limiting recovery
29.6,55.0,16.04,-0.5,0.9|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/8/below baseline, supporting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/2/a strong night, supporting recovery
29.6,55.0,17.5,0.1,0.6|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/8/below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
29.6,55.0,17.5,0.1,0.9|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/8/below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
29.6,55.0,17.5,0.25,0.6|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/8/below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
29.6,55.0,17.5,0.25,0.9|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/8/below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
29.6,55.0,17.5,-0.5,0.6|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/8/below baseline, supporting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/-12/below a good night, limiting recovery
29.6,55.0,17.5,-0.5,0.9|Heart rate variability/-1/slightly below baseline, limiting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/8/below baseline, supporting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/2/a strong night, supporting recovery
30.3,57.7,15.97,0.1,0.6|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
30.3,57.7,15.97,0.1,0.9|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
30.3,57.7,15.97,0.25,0.6|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
30.3,57.7,15.97,0.25,0.9|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
30.3,57.7,15.97,-0.5,0.6|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/-12/below a good night, limiting recovery
30.3,57.7,15.97,-0.5,0.9|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/2/a strong night, supporting recovery
30.3,57.7,16.04,0.1,0.6|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
30.3,57.7,16.04,0.1,0.9|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
30.3,57.7,16.04,0.25,0.6|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
30.3,57.7,16.04,0.25,0.9|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
30.3,57.7,16.04,-0.5,0.6|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/-12/below a good night, limiting recovery
30.3,57.7,16.04,-0.5,0.9|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/2/a strong night, supporting recovery
30.3,57.7,17.5,0.1,0.6|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
30.3,57.7,17.5,0.1,0.9|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
30.3,57.7,17.5,0.25,0.6|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
30.3,57.7,17.5,0.25,0.9|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
30.3,57.7,17.5,-0.5,0.6|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/-12/below a good night, limiting recovery
30.3,57.7,17.5,-0.5,0.9|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/2/a strong night, supporting recovery
30.3,58.3,15.97,0.1,0.6|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
30.3,58.3,15.97,0.1,0.9|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
30.3,58.3,15.97,0.25,0.6|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
30.3,58.3,15.97,0.25,0.9|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
30.3,58.3,15.97,-0.5,0.6|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/-12/below a good night, limiting recovery
30.3,58.3,15.97,-0.5,0.9|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/2/a strong night, supporting recovery
30.3,58.3,16.04,0.1,0.6|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
30.3,58.3,16.04,0.1,0.9|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
30.3,58.3,16.04,0.25,0.6|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
30.3,58.3,16.04,0.25,0.9|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
30.3,58.3,16.04,-0.5,0.6|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/-12/below a good night, limiting recovery
30.3,58.3,16.04,-0.5,0.9|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/2/a strong night, supporting recovery
30.3,58.3,17.5,0.1,0.6|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
30.3,58.3,17.5,0.1,0.9|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
30.3,58.3,17.5,0.25,0.6|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
30.3,58.3,17.5,0.25,0.9|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
30.3,58.3,17.5,-0.5,0.6|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/-12/below a good night, limiting recovery
30.3,58.3,17.5,-0.5,0.9|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/2/a strong night, supporting recovery
30.3,61.0,15.97,0.1,0.6|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/-8/above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
30.3,61.0,15.97,0.1,0.9|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/-8/above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
30.3,61.0,15.97,0.25,0.6|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/-8/above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
30.3,61.0,15.97,0.25,0.9|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/-8/above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
30.3,61.0,15.97,-0.5,0.6|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/-8/above baseline, limiting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/-12/below a good night, limiting recovery
30.3,61.0,15.97,-0.5,0.9|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/-8/above baseline, limiting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/2/a strong night, supporting recovery
30.3,61.0,16.04,0.1,0.6|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/-8/above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
30.3,61.0,16.04,0.1,0.9|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/-8/above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
30.3,61.0,16.04,0.25,0.6|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/-8/above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
30.3,61.0,16.04,0.25,0.9|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/-8/above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
30.3,61.0,16.04,-0.5,0.6|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/-8/above baseline, limiting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/-12/below a good night, limiting recovery
30.3,61.0,16.04,-0.5,0.9|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/-8/above baseline, limiting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/2/a strong night, supporting recovery
30.3,61.0,17.5,0.1,0.6|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/-8/above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
30.3,61.0,17.5,0.1,0.9|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/-8/above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
30.3,61.0,17.5,0.25,0.6|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/-8/above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
30.3,61.0,17.5,0.25,0.9|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/-8/above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
30.3,61.0,17.5,-0.5,0.6|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/-8/above baseline, limiting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/-12/below a good night, limiting recovery
30.3,61.0,17.5,-0.5,0.9|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/-8/above baseline, limiting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/2/a strong night, supporting recovery
30.3,55.0,15.97,0.1,0.6|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/8/below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
30.3,55.0,15.97,0.1,0.9|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/7/below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
30.3,55.0,15.97,0.25,0.6|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/8/below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
30.3,55.0,15.97,0.25,0.9|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/7/below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
30.3,55.0,15.97,-0.5,0.6|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/8/below baseline, supporting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/-12/below a good night, limiting recovery
30.3,55.0,15.97,-0.5,0.9|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/7/below baseline, supporting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/2/a strong night, supporting recovery
30.3,55.0,16.04,0.1,0.6|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/8/below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
30.3,55.0,16.04,0.1,0.9|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/7/below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
30.3,55.0,16.04,0.25,0.6|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/8/below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
30.3,55.0,16.04,0.25,0.9|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/7/below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
30.3,55.0,16.04,-0.5,0.6|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/8/below baseline, supporting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/-12/below a good night, limiting recovery
30.3,55.0,16.04,-0.5,0.9|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/7/below baseline, supporting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/2/a strong night, supporting recovery
30.3,55.0,17.5,0.1,0.6|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/8/below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
30.3,55.0,17.5,0.1,0.9|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/7/below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
30.3,55.0,17.5,0.25,0.6|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/8/below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
30.3,55.0,17.5,0.25,0.9|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/7/below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
30.3,55.0,17.5,-0.5,0.6|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/8/below baseline, supporting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/-12/below a good night, limiting recovery
30.3,55.0,17.5,-0.5,0.9|Heart rate variability/1/slightly above baseline, supporting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/7/below baseline, supporting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/2/a strong night, supporting recovery
31.0,57.7,15.97,0.1,0.6|Heart rate variability/4/above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
31.0,57.7,15.97,0.1,0.9|Heart rate variability/3/above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
31.0,57.7,15.97,0.25,0.6|Heart rate variability/4/above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
31.0,57.7,15.97,0.25,0.9|Heart rate variability/3/above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
31.0,57.7,15.97,-0.5,0.6|Heart rate variability/4/above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/-12/below a good night, limiting recovery
31.0,57.7,15.97,-0.5,0.9|Heart rate variability/3/above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/2/a strong night, supporting recovery
31.0,57.7,16.04,0.1,0.6|Heart rate variability/4/above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
31.0,57.7,16.04,0.1,0.9|Heart rate variability/3/above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
31.0,57.7,16.04,0.25,0.6|Heart rate variability/4/above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
31.0,57.7,16.04,0.25,0.9|Heart rate variability/3/above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
31.0,57.7,16.04,-0.5,0.6|Heart rate variability/4/above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/-12/below a good night, limiting recovery
31.0,57.7,16.04,-0.5,0.9|Heart rate variability/3/above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/2/a strong night, supporting recovery
31.0,57.7,17.5,0.1,0.6|Heart rate variability/4/above baseline, supporting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
31.0,57.7,17.5,0.1,0.9|Heart rate variability/3/above baseline, supporting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
31.0,57.7,17.5,0.25,0.6|Heart rate variability/4/above baseline, supporting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
31.0,57.7,17.5,0.25,0.9|Heart rate variability/3/above baseline, supporting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
31.0,57.7,17.5,-0.5,0.6|Heart rate variability/4/above baseline, supporting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/-12/below a good night, limiting recovery
31.0,57.7,17.5,-0.5,0.9|Heart rate variability/4/above baseline, supporting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/2/a strong night, supporting recovery
31.0,58.3,15.97,0.1,0.6|Heart rate variability/4/above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
31.0,58.3,15.97,0.1,0.9|Heart rate variability/3/above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
31.0,58.3,15.97,0.25,0.6|Heart rate variability/4/above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
31.0,58.3,15.97,0.25,0.9|Heart rate variability/3/above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
31.0,58.3,15.97,-0.5,0.6|Heart rate variability/4/above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/-12/below a good night, limiting recovery
31.0,58.3,15.97,-0.5,0.9|Heart rate variability/4/above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/2/a strong night, supporting recovery
31.0,58.3,16.04,0.1,0.6|Heart rate variability/4/above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
31.0,58.3,16.04,0.1,0.9|Heart rate variability/3/above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
31.0,58.3,16.04,0.25,0.6|Heart rate variability/4/above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
31.0,58.3,16.04,0.25,0.9|Heart rate variability/3/above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
31.0,58.3,16.04,-0.5,0.6|Heart rate variability/4/above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/-12/below a good night, limiting recovery
31.0,58.3,16.04,-0.5,0.9|Heart rate variability/4/above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/2/a strong night, supporting recovery
31.0,58.3,17.5,0.1,0.6|Heart rate variability/4/above baseline, supporting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
31.0,58.3,17.5,0.1,0.9|Heart rate variability/4/above baseline, supporting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
31.0,58.3,17.5,0.25,0.6|Heart rate variability/4/above baseline, supporting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
31.0,58.3,17.5,0.25,0.9|Heart rate variability/4/above baseline, supporting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
31.0,58.3,17.5,-0.5,0.6|Heart rate variability/4/above baseline, supporting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/-12/below a good night, limiting recovery
31.0,58.3,17.5,-0.5,0.9|Heart rate variability/4/above baseline, supporting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/2/a strong night, supporting recovery
31.0,61.0,15.97,0.1,0.6|Heart rate variability/3/above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/-8/above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
31.0,61.0,15.97,0.1,0.9|Heart rate variability/4/above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/-8/above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
31.0,61.0,15.97,0.25,0.6|Heart rate variability/3/above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/-8/above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
31.0,61.0,15.97,0.25,0.9|Heart rate variability/4/above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/-8/above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
31.0,61.0,15.97,-0.5,0.6|Heart rate variability/3/above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/-8/above baseline, limiting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/-12/below a good night, limiting recovery
31.0,61.0,15.97,-0.5,0.9|Heart rate variability/4/above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/-8/above baseline, limiting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/2/a strong night, supporting recovery
31.0,61.0,16.04,0.1,0.6|Heart rate variability/3/above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/-8/above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
31.0,61.0,16.04,0.1,0.9|Heart rate variability/4/above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/-8/above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
31.0,61.0,16.04,0.25,0.6|Heart rate variability/3/above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/-8/above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
31.0,61.0,16.04,0.25,0.9|Heart rate variability/4/above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/-8/above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
31.0,61.0,16.04,-0.5,0.6|Heart rate variability/3/above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/-8/above baseline, limiting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/-12/below a good night, limiting recovery
31.0,61.0,16.04,-0.5,0.9|Heart rate variability/4/above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/-8/above baseline, limiting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/2/a strong night, supporting recovery
31.0,61.0,17.5,0.1,0.6|Heart rate variability/3/above baseline, supporting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/-8/above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
31.0,61.0,17.5,0.1,0.9|Heart rate variability/4/above baseline, supporting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/-8/above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
31.0,61.0,17.5,0.25,0.6|Heart rate variability/3/above baseline, supporting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/-8/above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
31.0,61.0,17.5,0.25,0.9|Heart rate variability/4/above baseline, supporting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/-8/above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
31.0,61.0,17.5,-0.5,0.6|Heart rate variability/3/above baseline, supporting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/-8/above baseline, limiting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/-12/below a good night, limiting recovery
31.0,61.0,17.5,-0.5,0.9|Heart rate variability/4/above baseline, supporting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/-8/above baseline, limiting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/2/a strong night, supporting recovery
31.0,55.0,15.97,0.1,0.6|Heart rate variability/4/above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/8/below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
31.0,55.0,15.97,0.1,0.9|Heart rate variability/3/above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/7/below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
31.0,55.0,15.97,0.25,0.6|Heart rate variability/4/above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/8/below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
31.0,55.0,15.97,0.25,0.9|Heart rate variability/3/above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/7/below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
31.0,55.0,15.97,-0.5,0.6|Heart rate variability/4/above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/8/below baseline, supporting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/-12/below a good night, limiting recovery
31.0,55.0,15.97,-0.5,0.9|Heart rate variability/3/above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/7/below baseline, supporting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/2/a strong night, supporting recovery
31.0,55.0,16.04,0.1,0.6|Heart rate variability/4/above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/8/below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
31.0,55.0,16.04,0.1,0.9|Heart rate variability/3/above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/7/below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
31.0,55.0,16.04,0.25,0.6|Heart rate variability/4/above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/8/below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
31.0,55.0,16.04,0.25,0.9|Heart rate variability/3/above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/7/below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
31.0,55.0,16.04,-0.5,0.6|Heart rate variability/4/above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/8/below baseline, supporting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/-12/below a good night, limiting recovery
31.0,55.0,16.04,-0.5,0.9|Heart rate variability/3/above baseline, supporting recovery;Respiratory rate/0/at baseline;Resting heart rate/7/below baseline, supporting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/2/a strong night, supporting recovery
31.0,55.0,17.5,0.1,0.6|Heart rate variability/4/above baseline, supporting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/8/below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
31.0,55.0,17.5,0.1,0.9|Heart rate variability/3/above baseline, supporting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/7/below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
31.0,55.0,17.5,0.25,0.6|Heart rate variability/4/above baseline, supporting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/8/below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
31.0,55.0,17.5,0.25,0.9|Heart rate variability/3/above baseline, supporting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/7/below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
31.0,55.0,17.5,-0.5,0.6|Heart rate variability/4/above baseline, supporting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/8/below baseline, supporting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/-12/below a good night, limiting recovery
31.0,55.0,17.5,-0.5,0.9|Heart rate variability/3/above baseline, supporting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/7/below baseline, supporting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/2/a strong night, supporting recovery
24.0,57.7,15.97,0.1,0.6|Heart rate variability/-20/below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/-11/below a good night, limiting recovery
24.0,57.7,15.97,0.1,0.9|Heart rate variability/-22/below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
24.0,57.7,15.97,0.25,0.6|Heart rate variability/-20/below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/-11/below a good night, limiting recovery
24.0,57.7,15.97,0.25,0.9|Heart rate variability/-22/below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
24.0,57.7,15.97,-0.5,0.6|Heart rate variability/-20/below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/-11/below a good night, limiting recovery
24.0,57.7,15.97,-0.5,0.9|Heart rate variability/-22/below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/2/a strong night, supporting recovery
24.0,57.7,16.04,0.1,0.6|Heart rate variability/-20/below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/-11/below a good night, limiting recovery
24.0,57.7,16.04,0.1,0.9|Heart rate variability/-22/below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
24.0,57.7,16.04,0.25,0.6|Heart rate variability/-20/below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/-11/below a good night, limiting recovery
24.0,57.7,16.04,0.25,0.9|Heart rate variability/-22/below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
24.0,57.7,16.04,-0.5,0.6|Heart rate variability/-20/below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/-11/below a good night, limiting recovery
24.0,57.7,16.04,-0.5,0.9|Heart rate variability/-22/below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/2/a strong night, supporting recovery
24.0,57.7,17.5,0.1,0.6|Heart rate variability/-20/below baseline, limiting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/-10/below a good night, limiting recovery
24.0,57.7,17.5,0.1,0.9|Heart rate variability/-22/below baseline, limiting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
24.0,57.7,17.5,0.25,0.6|Heart rate variability/-20/below baseline, limiting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/-10/below a good night, limiting recovery
24.0,57.7,17.5,0.25,0.9|Heart rate variability/-22/below baseline, limiting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
24.0,57.7,17.5,-0.5,0.6|Heart rate variability/-19/below baseline, limiting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/-10/below a good night, limiting recovery
24.0,57.7,17.5,-0.5,0.9|Heart rate variability/-22/below baseline, limiting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/1/slightly below baseline, supporting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/2/a strong night, supporting recovery
24.0,58.3,15.97,0.1,0.6|Heart rate variability/-20/below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/-10/below a good night, limiting recovery
24.0,58.3,15.97,0.1,0.9|Heart rate variability/-22/below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
24.0,58.3,15.97,0.25,0.6|Heart rate variability/-19/below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/-10/below a good night, limiting recovery
24.0,58.3,15.97,0.25,0.9|Heart rate variability/-22/below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
24.0,58.3,15.97,-0.5,0.6|Heart rate variability/-19/below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/-10/below a good night, limiting recovery
24.0,58.3,15.97,-0.5,0.9|Heart rate variability/-22/below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/2/a strong night, supporting recovery
24.0,58.3,16.04,0.1,0.6|Heart rate variability/-20/below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/-10/below a good night, limiting recovery
24.0,58.3,16.04,0.1,0.9|Heart rate variability/-22/below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
24.0,58.3,16.04,0.25,0.6|Heart rate variability/-19/below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/-10/below a good night, limiting recovery
24.0,58.3,16.04,0.25,0.9|Heart rate variability/-22/below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
24.0,58.3,16.04,-0.5,0.6|Heart rate variability/-19/below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/-10/below a good night, limiting recovery
24.0,58.3,16.04,-0.5,0.9|Heart rate variability/-22/below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/2/a strong night, supporting recovery
24.0,58.3,17.5,0.1,0.6|Heart rate variability/-19/below baseline, limiting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/-10/below a good night, limiting recovery
24.0,58.3,17.5,0.1,0.9|Heart rate variability/-22/below baseline, limiting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
24.0,58.3,17.5,0.25,0.6|Heart rate variability/-19/below baseline, limiting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/-10/below a good night, limiting recovery
24.0,58.3,17.5,0.25,0.9|Heart rate variability/-22/below baseline, limiting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
24.0,58.3,17.5,-0.5,0.6|Heart rate variability/-19/below baseline, limiting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/-10/below a good night, limiting recovery
24.0,58.3,17.5,-0.5,0.9|Heart rate variability/-22/below baseline, limiting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/-1/slightly above baseline, limiting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/2/a strong night, supporting recovery
24.0,61.0,15.97,0.1,0.6|Heart rate variability/-18/below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/-6/above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/-9/below a good night, limiting recovery
24.0,61.0,15.97,0.1,0.9|Heart rate variability/-21/below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/-7/above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
24.0,61.0,15.97,0.25,0.6|Heart rate variability/-18/below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/-6/above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/-9/below a good night, limiting recovery
24.0,61.0,15.97,0.25,0.9|Heart rate variability/-21/below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/-7/above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
24.0,61.0,15.97,-0.5,0.6|Heart rate variability/-17/below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/-6/above baseline, limiting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/-9/below a good night, limiting recovery
24.0,61.0,15.97,-0.5,0.9|Heart rate variability/-21/below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/-7/above baseline, limiting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/2/a strong night, supporting recovery
24.0,61.0,16.04,0.1,0.6|Heart rate variability/-18/below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/-6/above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/-9/below a good night, limiting recovery
24.0,61.0,16.04,0.1,0.9|Heart rate variability/-21/below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/-7/above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
24.0,61.0,16.04,0.25,0.6|Heart rate variability/-17/below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/-6/above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/-9/below a good night, limiting recovery
24.0,61.0,16.04,0.25,0.9|Heart rate variability/-21/below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/-7/above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
24.0,61.0,16.04,-0.5,0.6|Heart rate variability/-17/below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/-6/above baseline, limiting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/-9/below a good night, limiting recovery
24.0,61.0,16.04,-0.5,0.9|Heart rate variability/-21/below baseline, limiting recovery;Respiratory rate/0/at baseline;Resting heart rate/-7/above baseline, limiting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/2/a strong night, supporting recovery
24.0,61.0,17.5,0.1,0.6|Heart rate variability/-17/below baseline, limiting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/-5/above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/-9/below a good night, limiting recovery
24.0,61.0,17.5,0.1,0.9|Heart rate variability/-21/below baseline, limiting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/-7/above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
24.0,61.0,17.5,0.25,0.6|Heart rate variability/-17/below baseline, limiting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/-5/above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/-9/below a good night, limiting recovery
24.0,61.0,17.5,0.25,0.9|Heart rate variability/-21/below baseline, limiting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/-7/above baseline, limiting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
24.0,61.0,17.5,-0.5,0.6|Heart rate variability/-17/below baseline, limiting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/-5/above baseline, limiting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/-9/below a good night, limiting recovery
24.0,61.0,17.5,-0.5,0.9|Heart rate variability/-21/below baseline, limiting recovery;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/-7/above baseline, limiting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/2/a strong night, supporting recovery
24.0,55.0,15.97,0.1,0.6|Heart rate variability/-21/below baseline, limiting recovery, though low resting HR suggests this may be parasympathetic saturation rather than fatigue;Respiratory rate/0/at baseline;Resting heart rate/7/below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
24.0,55.0,15.97,0.1,0.9|Heart rate variability/-21/below baseline, limiting recovery, though low resting HR suggests this may be parasympathetic saturation rather than fatigue;Respiratory rate/0/at baseline;Resting heart rate/8/below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
24.0,55.0,15.97,0.25,0.6|Heart rate variability/-21/below baseline, limiting recovery, though low resting HR suggests this may be parasympathetic saturation rather than fatigue;Respiratory rate/0/at baseline;Resting heart rate/7/below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
24.0,55.0,15.97,0.25,0.9|Heart rate variability/-21/below baseline, limiting recovery, though low resting HR suggests this may be parasympathetic saturation rather than fatigue;Respiratory rate/0/at baseline;Resting heart rate/8/below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
24.0,55.0,15.97,-0.5,0.6|Heart rate variability/-21/below baseline, limiting recovery, though low resting HR suggests this may be parasympathetic saturation rather than fatigue;Respiratory rate/0/at baseline;Resting heart rate/6/below baseline, supporting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/-12/below a good night, limiting recovery
24.0,55.0,15.97,-0.5,0.9|Heart rate variability/-21/below baseline, limiting recovery, though low resting HR suggests this may be parasympathetic saturation rather than fatigue;Respiratory rate/0/at baseline;Resting heart rate/8/below baseline, supporting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/2/a strong night, supporting recovery
24.0,55.0,16.04,0.1,0.6|Heart rate variability/-21/below baseline, limiting recovery, though low resting HR suggests this may be parasympathetic saturation rather than fatigue;Respiratory rate/0/at baseline;Resting heart rate/7/below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
24.0,55.0,16.04,0.1,0.9|Heart rate variability/-21/below baseline, limiting recovery, though low resting HR suggests this may be parasympathetic saturation rather than fatigue;Respiratory rate/0/at baseline;Resting heart rate/8/below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
24.0,55.0,16.04,0.25,0.6|Heart rate variability/-21/below baseline, limiting recovery, though low resting HR suggests this may be parasympathetic saturation rather than fatigue;Respiratory rate/0/at baseline;Resting heart rate/7/below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
24.0,55.0,16.04,0.25,0.9|Heart rate variability/-21/below baseline, limiting recovery, though low resting HR suggests this may be parasympathetic saturation rather than fatigue;Respiratory rate/0/at baseline;Resting heart rate/8/below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
24.0,55.0,16.04,-0.5,0.6|Heart rate variability/-21/below baseline, limiting recovery, though low resting HR suggests this may be parasympathetic saturation rather than fatigue;Respiratory rate/0/at baseline;Resting heart rate/6/below baseline, supporting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/-12/below a good night, limiting recovery
24.0,55.0,16.04,-0.5,0.9|Heart rate variability/-21/below baseline, limiting recovery, though low resting HR suggests this may be parasympathetic saturation rather than fatigue;Respiratory rate/0/at baseline;Resting heart rate/8/below baseline, supporting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/2/a strong night, supporting recovery
24.0,55.0,17.5,0.1,0.6|Heart rate variability/-21/below baseline, limiting recovery, though low resting HR suggests this may be parasympathetic saturation rather than fatigue;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/6/below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/-12/below a good night, limiting recovery
24.0,55.0,17.5,0.1,0.9|Heart rate variability/-21/below baseline, limiting recovery, though low resting HR suggests this may be parasympathetic saturation rather than fatigue;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/8/below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
24.0,55.0,17.5,0.25,0.6|Heart rate variability/-21/below baseline, limiting recovery, though low resting HR suggests this may be parasympathetic saturation rather than fatigue;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/6/below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/-11/below a good night, limiting recovery
24.0,55.0,17.5,0.25,0.9|Heart rate variability/-21/below baseline, limiting recovery, though low resting HR suggests this may be parasympathetic saturation rather than fatigue;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/8/below baseline, supporting recovery;Skin temperature/0/near baseline;Sleep quality/2/a strong night, supporting recovery
24.0,55.0,17.5,-0.5,0.6|Heart rate variability/-21/below baseline, limiting recovery, though low resting HR suggests this may be parasympathetic saturation rather than fatigue;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/6/below baseline, supporting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/-11/below a good night, limiting recovery
24.0,55.0,17.5,-0.5,0.9|Heart rate variability/-21/below baseline, limiting recovery, though low resting HR suggests this may be parasympathetic saturation rather than fatigue;Respiratory rate/-1/above baseline, limiting recovery;Resting heart rate/8/below baseline, supporting recovery;Skin temperature/-1/cooler than baseline, limiting recovery;Sleep quality/2/a strong night, supporting recovery
"""
    }
}
