import XCTest
@testable import StrandAnalytics

final class HRVCleaningPreservationTests: XCTestCase {
    // Generated by compiling original Swift at 8e94d559. Pin raw Double bits and removed-beat adjacency.
    private let originalOracle = """
0|0|cbf29ce484222325|cbf29ce484222325|cbf29ce484222325
1|0|cbf29ce484222325|cbf29ce484222325|cbf29ce484222325
2|1|2568834c8601b7df|2568834c8601b7df|af63bd4c8601b7df
3|2|205d8607b4eb6fed|205d8607b4eb6fed|8328707b4eb6e3a
4|3|75289a186c0f2fb7|75289a186c0f2fb7|d949ad186c0c4e41
5|4|2fe1767f9dce13f5|2fe1767f9dce13f5|447f607f98e8f6c0
6|5|1d42a1d9252be94f|1d42a1d9252be94f|4d67b9d0d3db49f3
7|6|8cf0b8fa299d713d|8cf0b8fa299d713d|628aafd7fd9ea636
8|7|1016fa14b6876aa7|1016fa14b6876aa7|104f0303f4946f75
9|3|34c79a186c0f2fb7|34c79a186c0f2fb7|d949ad186c0c4e41
10|1|2532234c8601b7df|2532234c8601b7df|af63bd4c8601b7df
11|7|585f1a14b6876aa7|585f1a14b6876aa7|104f0303f4946f75
12|3|30cc12186c0f2fb7|30cc12186c0f2fb7|d94d12186c0f2fb7
13|4|c532367f9dce13f5|c532367f9dce13f5|4d25757f9dce1242
14|300|ada53892fe7f4315|ada53892fe7f4315|ca507bed0f106018
15|284|53f2a91c3fc4d5d5|53f2a91c3fc4d5d5|ea13e2a443f8348a
16|36000|39399142eeffafa5|39399142eeffafa5|66887b7d4316484
17|34097|b9d60d46a4931f|b9d60d46a4931f|e1011fbbd685b430
18|108000|4529d5bc622088a5|4529d5bc622088a5|275d0339a0103744
19|102293|d16cc7e6a7b2c70f|d16cc7e6a7b2c70f|f9ef4947521f3074
"""

    private func cleaningOracleHash(_ words: [UInt64]) -> String {
        var hash: UInt64 = 14695981039346656037
        for word in words { hash = (hash ^ word) &* 1099511628211 }
        return String(hash, radix: 16)
    }

    private func cleaningOracleInput(_ count: Int, mixed: Bool) -> [Double] {
        (0..<count).map { i in
            if mixed && i % 31 == 0 { return 50 }
            if mixed && i % 47 == 0 { return 1500 }
            return 800 + Double((i * 17) % 101) / 4
        }
    }

    private var cleaningOracleFixtures: [[Double]] {
        var fixtures = (0...8).map { cleaningOracleInput($0, mixed: true) }
        fixtures += [[.nan, .infinity, -.infinity, 800, 801, 802],
                     [300, 299, 800.25, 1500, 801.5, 2000, 2001],
                     [800, 960, 800, 960, 800, 960, 800],
                     [800, 960.0000000000001, 800, 960.0000000000001, 800],
                     [2000, 2000, 1600, 1600, 300, 300, 300]]
        for count in [300, 36000, 108000] {
            fixtures.append(cleaningOracleInput(count, mixed: false))
            fixtures.append(cleaningOracleInput(count, mixed: true))
        }
        return fixtures
    }

    func testCleanRRPreservesOriginalBits() {
        let expected = originalOracle.split(separator: "\n").map { $0.split(separator: "|") }
        let fixtures = cleaningOracleFixtures
        guard expected.count == fixtures.count else { XCTFail("Oracle fixture count changed"); return }
        for (index, input) in fixtures.enumerated() {
            let before = input.map(\.bitPattern)
            let clean = HRVAnalyzer.cleanRR(input)
            XCTAssertEqual(String(clean.count), String(expected[index][1]), "case \(index)")
            XCTAssertEqual(cleaningOracleHash(clean.map(\.bitPattern)), String(expected[index][2]), "case \(index)")
            XCTAssertEqual(input.map(\.bitPattern), before)
            // Stop on a mismatch so an uncleared-buffer mutation never reaches the large fixtures.
            guard String(clean.count) == String(expected[index][1]),
                  cleaningOracleHash(clean.map(\.bitPattern)) == String(expected[index][2]) else { return }
        }
    }

    func testGapAwareCleaningPreservesOriginalBitsAndAdjacency() {
        let expected = originalOracle.split(separator: "\n").map { $0.split(separator: "|") }
        let fixtures = cleaningOracleFixtures
        guard expected.count == fixtures.count else { XCTFail("Oracle fixture count changed"); return }
        for (index, input) in fixtures.enumerated() {
            let before = input.map(\.bitPattern)
            let clean = HRVAnalyzer.cleanRRGapAware(input)
            XCTAssertEqual(String(clean.nn.count), String(expected[index][1]), "case \(index)")
            XCTAssertEqual(cleaningOracleHash(clean.nn.map(\.bitPattern)), String(expected[index][3]), "case \(index)")
            XCTAssertEqual(cleaningOracleHash(clean.contiguous.map { $0 ? 1 : 0 }), String(expected[index][4]), "case \(index)")
            XCTAssertEqual(input.map(\.bitPattern), before)
            guard String(clean.nn.count) == String(expected[index][1]),
                  cleaningOracleHash(clean.nn.map(\.bitPattern)) == String(expected[index][3]),
                  cleaningOracleHash(clean.contiguous.map { $0 ? 1 : 0 }) == String(expected[index][4]) else { return }
        }
    }
}
